Option Strict Off
Option Explicit On
<System.Runtime.InteropServices.ProgId("c_VariantSeq_NET.c_VariantSeq")> Public Class c_VariantSeq
	'Generated by IDL2VB v123. Copyright (c) 1999-2003 Martin.Both
	'Source File Name: ../include/CORBA.idl
	'Target File Name: c_VariantSeq.cls
	
	
	'IDL Name: sequence<long long>
	
	Private seqLen As Integer
	Private seqBnd As Integer
	Private seqArr() As Object
	Private seqIsDim As Boolean
	
	
	Public Property Length() As Integer
		Get
			Length = seqLen
		End Get
		Set(ByVal Value As Integer)
			On Error GoTo ErrHandler
			Dim newSize As Integer
			If Value <= 0 Then
				seqLen = 0
				Erase seqArr
				seqIsDim = False
			Else
				If seqBnd > 0 And Value > seqBnd Then
					Call mVBOrb.VBOrb.raiseBADPARAM(1, mVBOrb.VBOrb.CompletedNO, CStr(Value) & " > " & CStr(seqBnd))
				End If
				seqLen = Value
				If seqIsDim Then
					If Value > UBound(seqArr) + 1 Then
						newSize = (UBound(seqArr) * 3 + 3) \ 2
						If seqBnd > 0 And newSize > seqBnd Then
							newSize = seqBnd
						End If
						If Value > newSize Then
							newSize = Value
						End If
						ReDim Preserve seqArr(newSize - 1)
					End If
				Else
					ReDim seqArr(Value - 1)
					seqIsDim = True
				End If
			End If
			Exit Property
ErrHandler: 
			Call mVBOrb.VBOrb.ErrReraise(Err, "VariantSeq.Length.Let")
		End Set
	End Property
	
	Public ReadOnly Property Boundary() As Integer
		Get
			Boundary = seqBnd
		End Get
	End Property
	
	'index must be in the range of 0 to Length - 1
	
	'index must be in the range of 0 to Length - 1
	Public Property Item(ByVal index As Integer) As Object
		Get
			On Error GoTo ErrHandler
			'UPGRADE_WARNING: Couldn't resolve default property of object seqArr(index). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Item = seqArr(index)
			Exit Property
ErrHandler: 
			Call mVBOrb.VBOrb.ErrReraise(Err, "VariantSeq.Item.Get")
		End Get
		Set(ByVal Value As Object)
			On Error GoTo ErrHandler
			'UPGRADE_WARNING: Couldn't resolve default property of object Item. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object seqArr(index). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			seqArr(index) = Value
			Exit Property
ErrHandler: 
			Call mVBOrb.VBOrb.ErrReraise(Err, "VariantSeq.Item.Let")
		End Set
	End Property
	
	Public Function getItems(ByRef Arr() As Object) As Integer
		On Error GoTo ErrHandler
		getItems = seqLen
		Dim seqCnt As Integer
		For seqCnt = 0 To seqLen - 1
			'UPGRADE_WARNING: Couldn't resolve default property of object seqArr(seqCnt). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object Arr(LBound() + seqCnt). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			Arr(LBound(Arr) + seqCnt) = seqArr(seqCnt)
		Next seqCnt
		Exit Function
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "getItems")
	End Function
	
	Public Sub setItems(ByRef Arr() As Object, ByVal newLen As Integer)
		On Error GoTo ErrHandler
		Me.Length = newLen
		Dim seqCnt As Integer
		For seqCnt = 0 To seqLen - 1
			'UPGRADE_WARNING: Couldn't resolve default property of object Arr(LBound() + seqCnt). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object seqArr(seqCnt). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			seqArr(seqCnt) = Arr(LBound(Arr) + seqCnt)
		Next seqCnt
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "setItems")
	End Sub
	
	'Helper
	Public Sub initByRead(ByVal oIn As cOrbStream, ByVal maxLen As Integer)
		On Error GoTo ErrHandler
		seqBnd = maxLen
		Dim newLen As Integer
		newLen = oIn.readUlong()
		If seqBnd > 0 And newLen > seqBnd Then
			Call mVBOrb.VBOrb.raiseMARSHAL(1, mVBOrb.VBOrb.CompletedNO, CStr(newLen) & " > " & CStr(seqBnd))
		End If
		seqIsDim = False
		Me.Length = newLen
		Dim seqCnt As Integer
		For seqCnt = 0 To seqLen - 1
			'UPGRADE_WARNING: Couldn't resolve default property of object oIn.readLonglong(). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object seqArr(seqCnt). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			seqArr(seqCnt) = oIn.readLonglong()
		Next seqCnt
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "VariantSeq.read")
	End Sub
	
	'Helper
	Public Sub writeMe(ByVal oOut As cOrbStream, ByVal maxLen As Integer)
		On Error GoTo ErrHandler
		seqBnd = maxLen
		If seqBnd > 0 And seqLen > seqBnd Then
			Call mVBOrb.VBOrb.raiseMARSHAL(1, mVBOrb.VBOrb.CompletedNO, CStr(seqLen) & " > " & CStr(seqBnd))
		End If
		Call oOut.writeUlong(seqLen)
		Dim seqCnt As Integer
		For seqCnt = 0 To seqLen - 1
			Call oOut.writeLonglong(seqArr(seqCnt))
		Next seqCnt
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "VariantSeq.write")
	End Sub
	
	'Helper
	Public Sub initByAny(ByVal oAny As cOrbAny)
		On Error GoTo ErrHandler
		seqBnd = oAny.getOrigType.Length()
		Dim newLen As Integer
		newLen = oAny.seqGetLength()
		If seqBnd > 0 And newLen > seqBnd Then
			Call mVBOrb.VBOrb.raiseMARSHAL(1, mVBOrb.VBOrb.CompletedNO, CStr(newLen) & " > " & CStr(seqBnd))
		End If
		seqIsDim = False
		Me.Length = newLen
		Dim seqCnt As Integer
		For seqCnt = 0 To seqLen - 1
			'UPGRADE_WARNING: Couldn't resolve default property of object oAny.getLonglong(). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			'UPGRADE_WARNING: Couldn't resolve default property of object seqArr(seqCnt). Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
			seqArr(seqCnt) = oAny.getLonglong()
			Call oAny.nextPos()
		Next seqCnt
		Call oAny.rewind()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "initByAny")
	End Sub
	
	'Helper
	Public Sub insertIntoAny(ByVal oAny As cOrbAny)
		On Error GoTo ErrHandler
		Call oAny.seqSetLength(seqLen)
		Dim seqCnt As Integer
		For seqCnt = 0 To seqLen - 1
			Call oAny.insertLonglong(seqArr(seqCnt))
			Call oAny.nextPos()
		Next seqCnt
		Call oAny.rewind()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "insertIntoAny")
	End Sub
End Class