Option Strict Off
Option Explicit On
<System.Runtime.InteropServices.ProgId("cCBValueMember_NET.cCBValueMember")> Public Class cCBValueMember
	'Generated by IDL2VB v123. Copyright (c) 1999-2003 Martin.Both
	'Source File Name: ../include/CORBA.idl
	'Target File Name: cCBValueMember.cls
	
	
	'struct ::CORBA::ValueMember
	Const sTypeId As String = "IDL:omg.org/CORBA/ValueMember:1.0"
	
	'Member(s)
	Private name_ As String
	Private id_ As String
	Private defined_in_ As String
	Private version_ As String
	Private p_type_ As cOrbTypeCode
	Private type_def_ As cCBIDLType
	Private access_ As Short
	
	'Member: name
	
	Public Property name() As String
		Get
			name = name_
		End Get
		Set(ByVal Value As String)
			name_ = Value
		End Set
	End Property
	
	'Member: id
	
	Public Property id() As String
		Get
			id = id_
		End Get
		Set(ByVal Value As String)
			id_ = Value
		End Set
	End Property
	
	'Member: defined_in
	
	Public Property defined_in() As String
		Get
			defined_in = defined_in_
		End Get
		Set(ByVal Value As String)
			defined_in_ = Value
		End Set
	End Property
	
	'Member: version
	
	Public Property version() As String
		Get
			version = version_
		End Get
		Set(ByVal Value As String)
			version_ = Value
		End Set
	End Property
	
	'Member: type
	
	Public Property p_type() As cOrbTypeCode
		Get
			p_type = p_type_
		End Get
		Set(ByVal Value As cOrbTypeCode)
			p_type_ = Value
		End Set
	End Property
	
	'Member: type_def
	
	Public Property type_def() As cCBIDLType
		Get
			type_def = type_def_
		End Get
		Set(ByVal Value As cCBIDLType)
			type_def_ = Value
		End Set
	End Property
	
	'Member: access
	
	Public Property access() As Short
		Get
			access = access_
		End Get
		Set(ByVal Value As Short)
			access_ = Value
		End Set
	End Property
	
	'Helper
	Public Sub initByRead(ByVal oIn As cOrbStream)
		On Error GoTo ErrHandler
		name_ = oIn.readString()
		id_ = oIn.readString()
		defined_in_ = oIn.readString()
		version_ = oIn.readString()
		p_type_ = oIn.readTypeCode()
		type_def_ = mCBIDLType.narrow(oIn.readObject())
		access_ = oIn.readShort()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "ValueMember.read")
	End Sub
	
	'Helper
	Public Sub writeMe(ByVal oOut As cOrbStream)
		On Error GoTo ErrHandler
		Call oOut.writeString(name_)
		Call oOut.writeString(id_)
		Call oOut.writeString(defined_in_)
		Call oOut.writeString(version_)
		Call oOut.writeTypeCode(p_type_)
		'UPGRADE_WARNING: Couldn't resolve default property of object type_def_. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Call oOut.writeObject(type_def_)
		Call oOut.writeShort(access_)
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "ValueMember.write")
	End Sub
	
	'Helper
	Public Sub initByAny(ByVal oAny As cOrbAny)
		On Error GoTo ErrHandler
		name_ = oAny.getString()
		Call oAny.nextPos()
		id_ = oAny.getString()
		Call oAny.nextPos()
		defined_in_ = oAny.getString()
		Call oAny.nextPos()
		version_ = oAny.getString()
		Call oAny.nextPos()
		p_type_ = oAny.getTypecode()
		Call oAny.nextPos()
		type_def_ = oAny.getReference()
		Call oAny.nextPos()
		access_ = oAny.getShort()
		Call oAny.nextPos()
		Call oAny.rewind()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "initByAny")
	End Sub
	
	'Helper
	Public Sub insertIntoAny(ByVal oAny As cOrbAny)
		On Error GoTo ErrHandler
		Call oAny.insertString(name_)
		Call oAny.nextPos()
		Call oAny.insertString(id_)
		Call oAny.nextPos()
		Call oAny.insertString(defined_in_)
		Call oAny.nextPos()
		Call oAny.insertString(version_)
		Call oAny.nextPos()
		Call oAny.insertTypecode(p_type_)
		Call oAny.nextPos()
		'UPGRADE_WARNING: Couldn't resolve default property of object type_def_. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Call oAny.insertReference(type_def_)
		Call oAny.nextPos()
		Call oAny.insertShort(access_)
		Call oAny.nextPos()
		Call oAny.rewind()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "insertIntoAny")
	End Sub
End Class