Option Strict Off
Option Explicit On
<System.Runtime.InteropServices.ProgId("cCBWStringValue_NET.cCBWStringValue")> Public Class cCBWStringValue
	Implements _cOrbValueBase
	'Generated by IDL2VB v123. Copyright (c) 1999-2003 Martin.Both
	'Source File Name: ../include/CORBA.idl
	'Target File Name: cCBWStringValue.cls
	
	
	
	'valuetype ::CORBA::WStringValue
	Const sTypeId As String = "IDL:omg.org/CORBA/WStringValue:1.0"
	
	Private lUniqueId As Integer
	
	Private Value_ As String
	
	
	Public Property Value() As String
		Get
			Value = Value_
		End Get
		Set(ByVal Value As String)
			Value_ = Value
		End Set
	End Property
	
	'Helper to get different COM interface
	Friend Function thisOrbValueBase() As _cOrbValueBase
		thisOrbValueBase = Me
	End Function
	
	'Helper
	Private Function cOrbValueBase_UniqueId() As Integer Implements _cOrbValueBase.UniqueId
		If lUniqueId = 0 Then
			lUniqueId = mVBOrb.VBOrb.getNextUniqueID()
		End If
		cOrbValueBase_UniqueId = lUniqueId
	End Function
	
	'Helper
	Private Sub cOrbValueBase_initByRead(ByVal oIn As cOrbStream) Implements _cOrbValueBase.initByRead
		On Error GoTo ErrHandler
		Value_ = oIn.readWstring()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "WStringValue.read")
	End Sub
	
	'Helper
	Private Sub cOrbValueBase_writeMe(ByVal oOut As cOrbStream) Implements _cOrbValueBase.writeMe
		On Error GoTo ErrHandler
		Call oOut.writeWstring(Value_)
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "WStringValue.write")
	End Sub
	
	Private Function cOrbValueBase_getIds(ByVal Item As Short) As String Implements _cOrbValueBase.getIds
		cOrbValueBase_getIds = IIf(Item = 0, sTypeId, "")
	End Function
	
	Private Function cOrbValueBase_isCustom() As Boolean Implements _cOrbValueBase.isCustom
		cOrbValueBase_isCustom = False
	End Function
End Class