Option Strict Off
Option Explicit On
<System.Runtime.InteropServices.ProgId("c_LongSeqVF_NET.c_LongSeqVF")> Public Class c_LongSeqVF
	Implements _cOrbValueFactory
	'Generated by IDL2VB v123. Copyright (c) 1999-2003 Martin.Both
	'Source File Name: ../include/CORBA.idl
	'Target File Name: c_LongSeqVF.cls
	
	
	
	'Helper to get different COM interface
	Friend Function thisOrbValueFactory() As _cOrbValueFactory
		thisOrbValueFactory = Me
	End Function

	Private Function cOrbValueFactory_newUninitValue() As _cOrbValueBase Implements _cOrbValueFactory.newUninitValue

		cOrbValueFactory_newUninitValue = New c_LongSeq
	End Function
End Class