Option Strict Off
Option Explicit On
<System.Runtime.InteropServices.ProgId("cCBIDLType_NET.cCBIDLType")> Public Class cCBIDLType
	Implements _cOrbAbstractBase
	Implements _cOrbObject
	'Generated by IDL2VB v123. Copyright (c) 1999-2003 Martin.Both
	'Source File Name: ../include/CORBA.idl
	'Target File Name: cCBIDLType.cls
	
	
	
	'interface ::CORBA::IDLType
	Const sTypeId As String = "IDL:omg.org/CORBA/IDLType:1.0"
	Private oObjRef As cOrbObjRef
	
	'Helper to get different COM interface
	Friend Function thisOrbAbstractBase() As _cOrbAbstractBase
		thisOrbAbstractBase = Me
	End Function
	
	'Helper
	Private Function cOrbAbstractBase_isObjRef() As Boolean Implements _cOrbAbstractBase.isObjRef
		cOrbAbstractBase_isObjRef = True
	End Function
	
	'Helper to get different COM interface
	Friend Function thisOrbObject() As _cOrbObject
		thisOrbObject = Me
	End Function
	
	'Helper
	Private Function cOrbObject_setObjRef(ByVal ObjRef As cOrbObjRef, ByVal Check As Boolean) As Boolean Implements _cOrbObject.setObjRef
		On Error GoTo ErrHandler
		If ObjRef Is Nothing Then
			cOrbObject_setObjRef = True
		Else
			cOrbObject_setObjRef = False
			Call ObjRef.narrow(sTypeId, Check, False)
		End If
		oObjRef = ObjRef
		Exit Function
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "setObjRef")
	End Function
	
	'Helper
	Private Function cOrbObject_getObjRef() As cOrbObjRef Implements _cOrbObject.getObjRef
		cOrbObject_getObjRef = oObjRef
	End Function
	
	'Helper
	Private Function cOrbObject_getId() As String Implements _cOrbObject.getId
		cOrbObject_getId = sTypeId
	End Function
	
	'readonly attribute def_kind
	Public ReadOnly Property defKind() As Integer
		Get
			On Error GoTo ErrHandler
			Dim oRequest As cOrbRequest
			oRequest = oObjRef.request("_get_def_kind", False)
			Dim oIn As cOrbStream
			Call oRequest.invokeReqst(False)
			oIn = oRequest.OutRes
			defKind = oIn.readUlong()
			Exit Property
ErrHandler: 
			Call mVBOrb.VBOrb.ErrReraise(Err, "defKind.Get")
		End Get
	End Property
	
	'readonly attribute type
	Public ReadOnly Property typeProp() As cOrbTypeCode
		Get
			On Error GoTo ErrHandler
			Dim oRequest As cOrbRequest
			oRequest = oObjRef.request("_get_type", False)
			Dim oIn As cOrbStream
			Call oRequest.invokeReqst(False)
			oIn = oRequest.OutRes
			typeProp = oIn.readTypeCode()
			Exit Property
ErrHandler: 
			'UPGRADE_NOTE: Object typeProp may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
			typeProp = Nothing
			Call mVBOrb.VBOrb.ErrReraise(Err, "typeProp.Get")
		End Get
	End Property
	
	'destroy()
	Public Sub destroy()
		On Error GoTo ErrHandler
		Dim oRequest As cOrbRequest
		oRequest = oObjRef.request("destroy", False)
		Call oRequest.invokeReqst(False)
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "destroy")
	End Sub
End Class