Option Strict Off
Option Explicit On
<System.Runtime.InteropServices.ProgId("cCBUnionMember_NET.cCBUnionMember")> Public Class cCBUnionMember
	'Generated by IDL2VB v123. Copyright (c) 1999-2003 Martin.Both
	'Source File Name: ../include/CORBA.idl
	'Target File Name: cCBUnionMember.cls
	
	
	'struct ::CORBA::UnionMember
	Const sTypeId As String = "IDL:omg.org/CORBA/UnionMember:1.0"
	
	'Member(s)
	Private name_ As String
	Private label_ As cOrbAny
	Private p_type_ As cOrbTypeCode
	Private type_def_ As cCBIDLType
	
	'Member: name
	
	Public Property name() As String
		Get
			name = name_
		End Get
		Set(ByVal Value As String)
			name_ = Value
		End Set
	End Property
	
	'Member: label
	
	Public Property label() As cOrbAny
		Get
			label = label_
		End Get
		Set(ByVal Value As cOrbAny)
			label_ = Value
		End Set
	End Property
	
	'Member: type
	
	Public Property p_type() As cOrbTypeCode
		Get
			p_type = p_type_
		End Get
		Set(ByVal Value As cOrbTypeCode)
			p_type_ = Value
		End Set
	End Property
	
	'Member: type_def
	
	Public Property type_def() As cCBIDLType
		Get
			type_def = type_def_
		End Get
		Set(ByVal Value As cCBIDLType)
			type_def_ = Value
		End Set
	End Property
	
	'Helper
	Public Sub initByRead(ByVal oIn As cOrbStream)
		On Error GoTo ErrHandler
		name_ = oIn.readString()
		label_ = oIn.readAny()
		p_type_ = oIn.readTypeCode()
		type_def_ = mCBIDLType.narrow(oIn.readObject())
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "UnionMember.read")
	End Sub
	
	'Helper
	Public Sub writeMe(ByVal oOut As cOrbStream)
		On Error GoTo ErrHandler
		Call oOut.writeString(name_)
		Call oOut.writeAny(label_)
		Call oOut.writeTypeCode(p_type_)
		'UPGRADE_WARNING: Couldn't resolve default property of object type_def_. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Call oOut.writeObject(type_def_)
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "UnionMember.write")
	End Sub
	
	'Helper
	Public Sub initByAny(ByVal oAny As cOrbAny)
		On Error GoTo ErrHandler
		name_ = oAny.getString()
		Call oAny.nextPos()
		label_ = oAny.getAny()
		Call oAny.nextPos()
		p_type_ = oAny.getTypecode()
		Call oAny.nextPos()
		type_def_ = oAny.getReference()
		Call oAny.nextPos()
		Call oAny.rewind()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "initByAny")
	End Sub
	
	'Helper
	Public Sub insertIntoAny(ByVal oAny As cOrbAny)
		On Error GoTo ErrHandler
		Call oAny.insertString(name_)
		Call oAny.nextPos()
		Call oAny.insertAny(label_)
		Call oAny.nextPos()
		Call oAny.insertTypecode(p_type_)
		Call oAny.nextPos()
		'UPGRADE_WARNING: Couldn't resolve default property of object type_def_. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
		Call oAny.insertReference(type_def_)
		Call oAny.nextPos()
		Call oAny.rewind()
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "insertIntoAny")
	End Sub
End Class