Option Strict Off
Option Explicit On
<System.Runtime.InteropServices.ProgId("cOrbTypeCodeBounds_NET.cOrbTypeCodeBounds")> Public Class cOrbTypeCodeBounds
	Implements _cOrbException
	'Generated by IDL2VB v123. Copyright (c) 1999-2003 Martin.Both
	'Source File Name: ../include/TypeCode.idl
	'Target File Name: cOrbTypeCodeBounds.cls
	
	
	
	'exception ::CORBA::TypeCode::Bounds
	Const sTypeId As String = "IDL:omg.org/CORBA/TypeCode/Bounds:1.0"
	Private sSource As String
	Private sPostDescr As String
	
	'Helper to get different COM interface
	Public Function thisOrbException() As _cOrbException
		thisOrbException = Me
	End Function
	
	Private ReadOnly Property cOrbException_TypeId() As String Implements _cOrbException.TypeId
		Get
			cOrbException_TypeId = sTypeId
		End Get
	End Property
	
	Private ReadOnly Property cOrbException_Source() As String Implements _cOrbException.Source
		Get
			cOrbException_Source = sSource
		End Get
	End Property
	
	Private ReadOnly Property cOrbException_Description() As String Implements _cOrbException.Description
		Get
			'UPGRADE_WARNING: TypeName has a new behavior. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="9B7D5ADD-D8FE-4819-A36C-6DEDAF088CC7"'
			cOrbException_Description = "CORBA User Exception: [" & sTypeId & "], " & TypeName(Me) & sPostDescr
		End Get
	End Property
	
	Private Sub cOrbException_addInfos(Optional ByRef SourcePrefix As String = "", Optional ByRef PostDescr As String = "") Implements _cOrbException.addInfos
		If sSource = "" Then
			sSource = SourcePrefix
		ElseIf SourcePrefix <> "" Then 
			sSource = SourcePrefix & ": " & sSource
		End If
		If PostDescr <> "" Then
			sPostDescr = sPostDescr & ", " & PostDescr
		End If
	End Sub
	
	'Helper
	Private Sub cOrbException_initByRead(ByVal oIn As cOrbStream) Implements _cOrbException.initByRead
		On Error GoTo ErrHandler
		'There is nothing to read from oIn because this exception has no members
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "Bounds.read")
	End Sub
	
	'Helper
	Private Sub cOrbException_writeMe(ByVal oOut As cOrbStream) Implements _cOrbException.writeMe
		On Error GoTo ErrHandler
		Call oOut.writeString(sTypeId)
		Exit Sub
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "Bounds.write")
	End Sub
	
	'Helper
	Public Sub initByAny(ByVal oAny As cOrbAny)
		'There is nothing to get from oAny because this exception has no members
		Call oAny.rewind()
	End Sub
	
	'Helper
	Public Sub insertIntoAny(ByVal oAny As cOrbAny)
		'There is nothing to insert into oAny because this exception has no members
		Call oAny.rewind()
	End Sub
End Class