Option Strict Off
Option Explicit On
Module mCBIDLType
	'Generated by IDL2VB v123. Copyright (c) 2000-2003 Martin.Both
	'Source File Name: ../include/CORBA.idl
	
	
	'interface ::CORBA::IDLType
	Public Const TypeId As String = "IDL:omg.org/CORBA/IDLType:1.0"
	
	'Helper
	Public Function narrow(ByVal Obj As _cOrbObject) As cCBIDLType
		On Error GoTo ErrHandler
		Dim oObj As _cOrbObject
		If Obj Is Nothing Then
			'UPGRADE_NOTE: Object narrow may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
			narrow = Nothing
		Else
			oObj = New cCBIDLType
			If oObj.setObjRef(Obj.getObjRef(), True) Then
				'UPGRADE_NOTE: Object narrow may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
				narrow = Nothing
			Else
				narrow = oObj
			End If
		End If
		Exit Function
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "narrow")
	End Function
	
	'Helper
	Public Function uncheckedNarrow(ByVal Obj As _cOrbObject) As cCBIDLType
		On Error GoTo ErrHandler
		Dim oObj As _cOrbObject
		If Obj Is Nothing Then
			'UPGRADE_NOTE: Object uncheckedNarrow may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
			uncheckedNarrow = Nothing
		Else
			oObj = New cCBIDLType
			If oObj.setObjRef(Obj.getObjRef(), False) Then
				'UPGRADE_NOTE: Object uncheckedNarrow may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
				uncheckedNarrow = Nothing
			Else
				uncheckedNarrow = oObj
			End If
		End If
		Exit Function
ErrHandler: 
		Call mVBOrb.VBOrb.ErrReraise(Err, "uncheckedNarrow")
	End Function
End Module